import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./global.css";
import "react-skeletonify/dist/index.css";
import { CssBaseline } from "@mui/material";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Waylone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <CssBaseline /> */}
        {children}
      </body>
    </html>
  );
}

